wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1670163742.95006
    t:
      1:
      - 1
      - 5
      - 30
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 30
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 23
      4: 3.9.7
      5: 0.13.5
      8:
      - 5
