
dataset: cifar10
model: resnet20
non_iid: False
alpha: 0.1
num_clients: 100
num_byzantine: 0
#trusted_id: 49
client_momentum: 0.0

attack: ALIE
attack_kws: {"num_clients": 16, "num_byzantine": 0}

# agg: Geomed
agg: Median
# agg: Mean
#aggregator_kws: {num_excluded: 1, k: 5}
#aggregator_kws: {"linkage": "average"}

gpu_server: 0.2
algorithm: fedsgd

local_round: 1
global_round: 2000
serv_momentum: 0.0
batch_size: 128
test_batch_size: 128
validate_interval: 100


bucketing: 0
#Ray related configurations.

# If you try to debug the code, use `local_mode:True`
local_mode: False
num_actors: 1
gpu_per_actor: 0.09
