
dataset: cifar10
model:
non_iid: False
alpha: 0.1
num_clients: 40
num_byzantine: 5
#trusted_id: 49
client_momentum: 0.99

attack: ALIE
attack_kws: {"num_clients": 40, "num_byzantine": 5}

agg: Median
#aggregator_kws: {num_excluded: 1, k: 5}
#aggregator_kws: {"linkage": "average"}

gpu_server: 0.2
algorithm: fedsgd

local_round: 1
global_round: 1000
serv_momentum: 0.0
batch_size: 128
test_batch_size: 128
validate_interval: 100


bucketing: 0
#Ray related configurations.

# If you try to debug the code, use `local_mode:True`
local_mode: False
num_actors: 1
gpu_per_actor: 0.09
