
dataset: cifar10
non_iid: False
alpha: 0.1
num_clients: 50
num_byzantine: 0
#trusted_id: 49


attack: ALIE
attack_kws: {"num_clients": 50, "num_byzantine": 0}

agg: Median
#aggregator_kws: {num_excluded: 1, k: 5}
#aggregator_kws: {"linkage": "average"}

gpu_server: 0.2
algorithm: fedsgd

local_round: 1
global_round: 6000
serv_momentum: 0.9
batch_size: 64
test_batch_size: 128
validate_interval: 50


#Ray related configurations.

# If you try to debug the code, use `local_mode:True`
local_mode: False
num_actors: 4
gpu_per_actor: 0.19
