name: Testing Installation

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:

  import:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        torch-version: [1.12.0]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          pip install numpy typing-extensions dataclasses
          pip install torch==${{ matrix.torch-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install torchvision


      - name: Test torch imports
        run: |
          python -c "import torch"

      - name: Install Blades
        run: |
          cd src
          pip install -e .

      - name: Test imports
        run: |
          python -c "import blades"

      - name: Run tests
        run: |
          pip install pytest
          pytest
